// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNgSVaLxP-VQFyMNtJLAvlFgQPqZkjoJE',
    appId: '1:347561737536:web:8b5d2cee1758e66e878ea5',
    messagingSenderId: '347561737536',
    projectId: 'cart-page-credenz',
    authDomain: 'cart-page-credenz.firebaseapp.com',
    storageBucket: 'cart-page-credenz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-amGZ6iAC5yN9_jqNqYiyeCLiljJetkE',
    appId: '1:347561737536:android:17024123dce7933b878ea5',
    messagingSenderId: '347561737536',
    projectId: 'cart-page-credenz',
    storageBucket: 'cart-page-credenz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2bcGnL2gVAhXMYVo9N51xXR5nBnSsSsc',
    appId: '1:347561737536:ios:5b00dbae0c4c9d0c878ea5',
    messagingSenderId: '347561737536',
    projectId: 'cart-page-credenz',
    storageBucket: 'cart-page-credenz.appspot.com',
    iosBundleId: 'com.example.cartPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2bcGnL2gVAhXMYVo9N51xXR5nBnSsSsc',
    appId: '1:347561737536:ios:71cc724d13d4b89e878ea5',
    messagingSenderId: '347561737536',
    projectId: 'cart-page-credenz',
    storageBucket: 'cart-page-credenz.appspot.com',
    iosBundleId: 'com.example.cartPage.RunnerTests',
  );
}
